package com.fusi24.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HomepageDesign extends VerticalLayout {
    protected VerticalLayout header;
    protected VerticalLayout body;
    protected VerticalLayout navLayout;
    protected Button sampleButton;
    protected VerticalLayout viewContent;
    protected Panel viewPanel;

    public HomepageDesign() {
		Design.read(this);
	}
}
