package com.app.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.PasswordField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AccountDesign extends HorizontalLayout {
    protected TextField txtUsername;
    protected TextField txtEmail;
    protected PasswordField txtPassword;
    protected Button btnSimpan;
    protected Button btnRefresh;
    protected Grid<com.app.model.Acount> accountGrid;

    public AccountDesign() {
        Design.read(this);
    }
}
