package com.app.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HomePageDesign extends VerticalLayout {
    protected VerticalLayout header;
    protected VerticalLayout body;
    protected VerticalLayout navLayout;
    protected Button sampleButton;
    protected VerticalLayout viewContent;
    protected Panel viewPanel;

    public HomePageDesign() {
        Design.read(this);
    }
}
